/* tslint:disable */
/* eslint-disable */

export class HwpDocument {
    free(): void;
    [Symbol.dispose](): void;
    addBookmark(section_idx: number, paragraph_idx: number, char_offset: number, name: string): string;
    applyCellStyle(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, style_id: number): string;
    applyCharFormat(section_idx: number, para_idx: number, start_offset: number, end_offset: number, props_json: string): string;
    applyCharFormatInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, start_offset: number, end_offset: number, props_json: string): string;
    applyEndnoteShape(section_idx: number, props_json: string): string;
    applyHfTemplate(section_idx: number, is_header: boolean, apply_to: number, template_id: number): string;
    applyParaFormat(section_idx: number, para_idx: number, props_json: string): string;
    applyParaFormatInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, props_json: string): string;
    applyParaFormatInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number, props_json: string): string;
    applyParaFormatInHf(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number, props_json: string): string;
    applyStyle(section_idx: number, para_idx: number, style_id: number): string;
    changeShapeZOrder(section_idx: number, parent_para_idx: number, control_idx: number, operation: string): string;
    clearActiveField(): void;
    clearClipboard(): void;
    clipboardHasControl(): boolean;
    convertToEditable(): string;
    copyControl(section_idx: number, paragraph_idx: number, cell_path_json: string, control_idx: number): string;
    copySelection(section_idx: number, start_para_idx: number, start_char_offset: number, end_para_idx: number, end_char_offset: number): string;
    copySelectionInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, start_cell_para_idx: number, start_char_offset: number, end_cell_para_idx: number, end_char_offset: number): string;
    createBlankDocument(): string;
    static createEmpty(): HwpDocument;
    createHeaderFooter(section_idx: number, is_header: boolean, apply_to: number): string;
    createNumbering(json: string): number;
    createShapeControl(params_json: string): string;
    createStyle(json: string): number;
    createTable(section_idx: number, paragraph_idx: number, char_offset: number, rows: number, cols: number): string;
    debugDumpStableIds(section_idx: number, start_para: number, count: number): string;
    deleteBookmark(section_idx: number, paragraph_idx: number, control_idx: number): string;
    deleteCellPictureControlByPath(section_idx: number, parent_para_idx: number, cell_path_json: string, inner_control_idx: number): string;
    deleteEquationControl(section_idx: number, parent_para_idx: number, control_idx: number): string;
    deleteFootnote(section_idx: number, para_idx: number, control_idx: number): string;
    deleteHeaderFooter(section_idx: number, is_header: boolean, apply_to: number): void;
    deletePictureControl(section_idx: number, parent_para_idx: number, control_idx: number): string;
    deleteRange(section_idx: number, start_para_idx: number, start_char_offset: number, end_para_idx: number, end_char_offset: number): string;
    deleteRangeInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, start_cell_para_idx: number, start_char_offset: number, end_cell_para_idx: number, end_char_offset: number): string;
    deleteShapeControl(section_idx: number, parent_para_idx: number, control_idx: number): string;
    deleteStyle(style_id: number): boolean;
    deleteTableColumn(section_idx: number, parent_para_idx: number, control_idx: number, col_idx: number): string;
    deleteTableControl(section_idx: number, parent_para_idx: number, control_idx: number): string;
    deleteTableRow(section_idx: number, parent_para_idx: number, control_idx: number, row_idx: number): string;
    deleteText(section_idx: number, para_idx: number, char_offset: number, count: number): string;
    deleteTextInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, count: number): string;
    deleteTextInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number, count: number): string;
    deleteTextInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number, char_offset: number, count: number): string;
    deleteTextInHeaderFooter(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number, char_offset: number, count: number): string;
    discardSnapshot(id: number): void;
    ensureDefaultBullet(bullet_char: string): number;
    ensureDefaultNumbering(): number;
    ensureParagraphStableIds(): void;
    evaluateTableFormula(section_idx: number, parent_para_idx: number, control_idx: number, target_row: number, target_col: number, formula: string, write_result: boolean): string;
    exportControlHtml(section_idx: number, paragraph_idx: number, cell_path_json: string, control_idx: number): string;
    exportHwp(): Uint8Array;
    exportHwpVerify(): string;
    exportHwpx(): Uint8Array;
    exportSelectionHtml(section_idx: number, start_para_idx: number, start_char_offset: number, end_para_idx: number, end_char_offset: number): string;
    exportSelectionInCellHtml(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, start_cell_para: number, start_offset: number, end_cell_para: number, end_offset: number): string;
    findNearestControlBackward(section_idx: number, para_idx: number, char_offset: number): string;
    findNearestControlForward(section_idx: number, para_idx: number, char_offset: number): string;
    findNextEditableControl(section_idx: number, para_idx: number, control_idx: number, delta: number): string;
    findOrCreateFontId(name: string): number;
    findOrCreateFontIdForLang(lang: number, name: string): number;
    getBookmarks(): string;
    getBulletList(): string;
    getCanvasKitReplayPlan(page_num: number, mode: string): string;
    getCaretPosition(): string;
    getCellCharPropertiesAt(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number): string;
    getCellInfo(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number): string;
    getCellInfoByPath(section_idx: number, parent_para_idx: number, path_json: string): string;
    getCellParaPropertiesAt(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number): string;
    getCellParagraphCount(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number): number;
    getCellParagraphCountByPath(section_idx: number, parent_para_idx: number, path_json: string): number;
    getCellParagraphLength(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number): number;
    getCellParagraphLengthByPath(section_idx: number, parent_para_idx: number, path_json: string): number;
    getCellPicturePropertiesByPath(section_idx: number, parent_para_idx: number, cell_path_json: string, inner_control_idx: number): string;
    getCellProperties(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number): string;
    getCellShapePropertiesByPath(section_idx: number, parent_para_idx: number, cell_path_json: string, inner_control_idx: number): string;
    getCellStyleAt(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number): string;
    getCellTextDirection(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number): number;
    getCharPropertiesAt(section_idx: number, para_idx: number, char_offset: number): string;
    getClickHereProps(field_id: number): string;
    getClipboardText(): string;
    getColumnDef(section_idx: number): string;
    getControlImageData(section_idx: number, paragraph_idx: number, cell_path_json: string, control_idx: number): Uint8Array;
    getControlImageMime(section_idx: number, paragraph_idx: number, cell_path_json: string, control_idx: number): string;
    getControlTextPositions(section_idx: number, para_idx: number): string;
    getCursorRect(section_idx: number, para_idx: number, char_offset: number): string;
    getCursorRectByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number): string;
    getCursorRectInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number): string;
    getCursorRectInFootnote(page_num: number, footnote_index: number, fn_para_idx: number, char_offset: number): string;
    getCursorRectInHeaderFooter(page_num: number, is_header: boolean, apply_to: number, hf_para_idx: number, char_offset: number, preferred_page: number): string;
    getCursorRectInNote(section_idx: number, paragraph_idx: number, control_idx: number, note_para_idx: number, char_offset: number): string;
    getDocumentInfo(): string;
    getDpi(): number;
    getEndnoteShape(section_idx: number): string;
    getEquationProperties(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number): string;
    getExternalImageBasenames(): string;
    getFieldInfoAt(section_idx: number, para_idx: number, char_offset: number): string;
    getFieldInfoAtByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number): string;
    getFieldInfoAtInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, is_textbox: boolean): string;
    getFieldList(): string;
    getFieldValue(field_id: number): string;
    getFieldValueByName(name: string): string;
    getFootnoteInfo(section_idx: number, para_idx: number, control_idx: number): string;
    getFormObjectAt(page_num: number, x: number, y: number): string;
    getFormObjectInfo(section_idx: number, paragraph_idx: number, control_idx: number): string;
    getFormValue(section_idx: number, paragraph_idx: number, control_idx: number): string;
    getHeaderFooter(section_idx: number, is_header: boolean, apply_to: number): string;
    getHeaderFooterList(current_section_idx: number, current_is_header: boolean, current_apply_to: number): string;
    getHeaderFooterParaInfo(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number): string;
    getHeaderFooterPictureProperties(section_idx: number, outer_para_idx: number, outer_control_idx: number, inner_para_idx: number, inner_control_idx: number): string;
    getLineInfo(section_idx: number, para_idx: number, char_offset: number): string;
    getLineInfoInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number): string;
    getNoteEditInfo(section_idx: number, para_idx: number, control_idx: number): string;
    getNoteEquationProperties(section_idx: number, para_idx: number, control_idx: number, note_para_idx: number, equation_idx: number): string;
    getNumberingList(): string;
    getPageBorderFill(section_idx: number): string;
    getPageControlLayout(page_num: number): string;
    getPageDef(section_idx: number): string;
    getPageFootnoteInfo(page_num: number, footnote_index: number): string;
    getPageInfo(page_num: number): string;
    getPageLayerTree(page_num: number): string;
    getPageLayerTreeWithProfile(page_num: number, profile: string): string;
    getPageOfPosition(section_idx: number, para_idx: number): string;
    getPageOverlayImages(page_num: number): string;
    getParaPropertiesAt(section_idx: number, para_idx: number): string;
    getParaPropertiesInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number): string;
    getParaPropertiesInHf(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number): string;
    getParagraphCount(section_idx: number): number;
    getParagraphLength(section_idx: number, para_idx: number): number;
    getParagraphStableId(section_idx: number, paragraph_idx: number): string;
    getPictureProperties(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getPositionOfPage(global_page: number): string;
    getSectionCount(): number;
    getSectionDef(section_idx: number): string;
    getSelectionRects(section_idx: number, start_para_idx: number, start_char_offset: number, end_para_idx: number, end_char_offset: number): string;
    getSelectionRectsInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, start_cell_para_idx: number, start_char_offset: number, end_cell_para_idx: number, end_char_offset: number): string;
    getSelectionRectsInFootnote(page_num: number, footnote_index: number, start_fn_para: number, start_offset: number, end_fn_para: number, end_offset: number): string;
    getShapeBBox(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getShapeProperties(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getShapeText(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getShowControlCodes(): boolean;
    getShowTransparentBorders(): boolean;
    getSourceFormat(): string;
    getStyleAt(section_idx: number, para_idx: number): string;
    getStyleDetail(style_id: number): string;
    getStyleList(): string;
    getTableBBox(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getTableCellBboxes(section_idx: number, parent_para_idx: number, control_idx: number, page_hint?: number | null): string;
    getTableCellBboxesByPath(section_idx: number, parent_para_idx: number, path_json: string): string;
    getTableDimensions(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getTableDimensionsByPath(section_idx: number, parent_para_idx: number, path_json: string): string;
    getTableProperties(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getTableSignature(section_idx: number, parent_para_idx: number, control_idx: number): string;
    getTextBoxControlIndex(section_idx: number, para_idx: number): number;
    getTextInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, count: number): string;
    getTextInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number, count: number): string;
    getTextRange(section_idx: number, para_idx: number, char_offset: number, count: number): string;
    getValidationWarnings(): string;
    groupShapes(json: string): string;
    hasInternalClipboard(): boolean;
    hitTest(page_num: number, x: number, y: number): string;
    hitTestBodyFootnoteMarker(page_num: number, x: number, y: number): string;
    hitTestFootnote(page_num: number, x: number, y: number): string;
    hitTestHeaderFooter(page_num: number, x: number, y: number): string;
    hitTestInFootnote(page_num: number, x: number, y: number): string;
    hitTestInHeaderFooter(page_num: number, _is_header: boolean, x: number, y: number): string;
    injectExternalImage(name: string, bytes: Uint8Array, display_path: string): number;
    insertColumnBreak(section_idx: number, paragraph_idx: number, char_offset: number): string;
    insertEndnote(section_idx: number, para_idx: number, char_offset: number): string;
    insertEquation(section_idx: number, paragraph_idx: number, char_offset: number, script: string, font_size: number, color: number): string;
    insertFieldInHf(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number, char_offset: number, field_type: number): string;
    insertFootnote(section_idx: number, para_idx: number, char_offset: number): string;
    insertNewNumber(section_idx: number, paragraph_idx: number, char_offset: number, start_num: number): string;
    insertPageBreak(section_idx: number, paragraph_idx: number, char_offset: number): string;
    insertPicture(section_idx: number, paragraph_idx: number, char_offset: number, cell_path_json: string, image_data: Uint8Array, width: number, height: number, natural_width_px: number, natural_height_px: number, extension: string, description: string, paper_offset_x_hu?: number | null, paper_offset_y_hu?: number | null): string;
    insertTableColumn(section_idx: number, parent_para_idx: number, control_idx: number, col_idx: number, right: boolean): string;
    insertTableRow(section_idx: number, parent_para_idx: number, control_idx: number, row_idx: number, below: boolean): string;
    insertText(section_idx: number, para_idx: number, char_offset: number, text: string): string;
    insertTextInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, text: string): string;
    insertTextInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number, text: string): string;
    insertTextInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number, char_offset: number, text: string): string;
    insertTextInHeaderFooter(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number, char_offset: number, text: string): string;
    mergeParagraph(section_idx: number, para_idx: number): string;
    mergeParagraphInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number): string;
    mergeParagraphInCellByPath(section_idx: number, parent_para_idx: number, path_json: string): string;
    mergeParagraphInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number): string;
    mergeParagraphInHeaderFooter(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number): string;
    mergeTableCells(section_idx: number, parent_para_idx: number, control_idx: number, start_row: number, start_col: number, end_row: number, end_col: number): string;
    moveLineEndpoint(section_idx: number, parent_para_idx: number, control_idx: number, sx: number, sy: number, ex: number, ey: number): string;
    moveTableOffset(section_idx: number, parent_para_idx: number, control_idx: number, delta_h: number, delta_v: number): string;
    moveVertical(section_idx: number, para_idx: number, char_offset: number, delta: number, preferred_x: number, _parent_para_idx: number, _control_idx: number, _cell_idx: number, _cell_para_idx: number): string;
    moveVerticalByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number, delta: number, preferred_x: number): string;
    navigateHeaderFooterByPage(current_page: number, is_header: boolean, direction: number): string;
    navigateNextEditable(section_idx: number, para_idx: number, char_offset: number, delta: number, context_json: string): string;
    constructor(data: Uint8Array);
    pageCount(): number;
    pasteControl(section_idx: number, paragraph_idx: number, char_offset: number): string;
    pasteHtml(section_idx: number, paragraph_idx: number, char_offset: number, html: string): string;
    pasteHtmlInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, html: string): string;
    pasteHtmlInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number, html: string): string;
    pasteInternal(section_idx: number, para_idx: number, char_offset: number): string;
    pasteInternalInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number): string;
    pasteInternalInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number): string;
    plainText(): string;
    reflowLinesegs(): number;
    refreshLayout(): void;
    removeFieldAt(section_idx: number, para_idx: number, char_offset: number): string;
    removeFieldAtInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, is_textbox: boolean): string;
    renameBookmark(section_idx: number, paragraph_idx: number, control_idx: number, new_name: string): string;
    renderEquationPreview(script: string, font_size_hwpunit: number, color: number): string;
    renderPageHtml(page_num: number): string;
    renderPageSvg(page_num: number): string;
    renderPageToCanvas(page_num: number, canvas: HTMLCanvasElement, scale: number): void;
    renderPageToCanvasFiltered(page_num: number, canvas: HTMLCanvasElement, scale: number, _layer_kind: string): void;
    renderPageToCanvasLegacy(page_num: number, canvas: HTMLCanvasElement, scale: number): void;
    replaceAll(query: string, new_text: string, case_sensitive: boolean): string;
    replaceOne(query: string, new_text: string, case_sensitive: boolean): string;
    replaceText(section_idx: number, para_idx: number, char_offset: number, length: number, new_text: string): string;
    resizeTableCells(section_idx: number, parent_para_idx: number, control_idx: number, updates_json: string): string;
    restoreSnapshot(id: number): string;
    saveSnapshot(): number;
    searchAllText(query: string, case_sensitive: boolean, include_cells: boolean): string;
    searchText(query: string, from_sec: number, from_para: number, from_char: number, forward: boolean, case_sensitive: boolean): string;
    setActiveField(section_idx: number, para_idx: number, char_offset: number): boolean;
    setActiveFieldByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number): boolean;
    setActiveFieldInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number, is_textbox: boolean): boolean;
    setCellPicturePropertiesByPath(section_idx: number, parent_para_idx: number, cell_path_json: string, inner_control_idx: number, props_json: string): string;
    setCellProperties(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, props_json: string): string;
    setCellShapePropertiesByPath(section_idx: number, parent_para_idx: number, cell_path_json: string, inner_control_idx: number, props_json: string): string;
    setClipEnabled(enabled: boolean): void;
    setColumnDef(section_idx: number, column_count: number, column_type: number, same_width: number, spacing_hu: number): string;
    setDpi(dpi: number): void;
    setEquationProperties(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, props_json: string): string;
    setFieldValue(field_id: number, value: string): string;
    setFieldValueByName(name: string, value: string): string;
    setFileName(name: string): void;
    setFormValue(section_idx: number, paragraph_idx: number, control_idx: number, value_json: string): string;
    setFormValueInCell(section_idx: number, table_para: number, table_ci: number, cell_idx: number, cell_para: number, form_ci: number, value_json: string): string;
    setHeaderFooterPictureProperties(section_idx: number, outer_para_idx: number, outer_control_idx: number, inner_para_idx: number, inner_control_idx: number, props_json: string): string;
    setNoteEquationProperties(section_idx: number, para_idx: number, control_idx: number, note_para_idx: number, equation_idx: number, props_json: string): string;
    setNumberingRestart(section_idx: number, paragraph_idx: number, mode: number, start_num: number): string;
    setPageBorderFill(section_idx: number, settings_json: string): string;
    setPageDef(section_idx: number, page_def_json: string): string;
    setPictureProperties(section_idx: number, parent_para_idx: number, control_idx: number, props_json: string): string;
    setSectionDef(section_idx: number, section_def_json: string): string;
    setSectionDefAll(section_def_json: string): string;
    setShapeProperties(section_idx: number, parent_para_idx: number, control_idx: number, props_json: string): string;
    setShowControlCodes(enabled: boolean): void;
    setShowParagraphMarks(enabled: boolean): void;
    setShowTransparentBorders(enabled: boolean): void;
    setTableProperties(section_idx: number, parent_para_idx: number, control_idx: number, props_json: string): string;
    splitParagraph(section_idx: number, para_idx: number, char_offset: number): string;
    splitParagraphInCell(section_idx: number, parent_para_idx: number, control_idx: number, cell_idx: number, cell_para_idx: number, char_offset: number): string;
    splitParagraphInCellByPath(section_idx: number, parent_para_idx: number, path_json: string, char_offset: number): string;
    splitParagraphInFootnote(section_idx: number, paragraph_idx: number, control_idx: number, fn_para_idx: number, char_offset: number): string;
    splitParagraphInHeaderFooter(section_idx: number, is_header: boolean, apply_to: number, hf_para_idx: number, char_offset: number): string;
    splitTableCell(section_idx: number, parent_para_idx: number, control_idx: number, row: number, col: number): string;
    splitTableCellInto(section_idx: number, parent_para_idx: number, control_idx: number, row: number, col: number, n_rows: number, m_cols: number, equal_row_height: boolean, merge_first: boolean): string;
    splitTableCellsInRange(section_idx: number, parent_para_idx: number, control_idx: number, start_row: number, start_col: number, end_row: number, end_col: number, n_rows: number, m_cols: number, equal_row_height: boolean): string;
    toggleHideHeaderFooter(page_num: number, is_header: boolean): string;
    ungroupShape(section_idx: number, parent_para_idx: number, control_idx: number): string;
    updateClickHereProps(field_id: number, guide: string, memo: string, name: string, editable: boolean): string;
    updateConnectorsInSection(section_idx: number): void;
    updateStyle(style_id: number, json: string): boolean;
    updateStyleShapes(style_id: number, char_mods_json: string, para_mods_json: string): boolean;
}

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly __wbg_hwpdocument_free: (a: number, b: number) => void;
    readonly hwpdocument_addBookmark: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_applyCellStyle: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_applyCharFormat: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_applyCharFormatInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
    readonly hwpdocument_applyEndnoteShape: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_applyHfTemplate: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_applyParaFormat: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_applyParaFormatInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_applyParaFormatInFootnote: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_applyParaFormatInHf: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_applyStyle: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_changeShapeZOrder: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_clearActiveField: (a: number) => void;
    readonly hwpdocument_clearClipboard: (a: number) => void;
    readonly hwpdocument_clipboardHasControl: (a: number) => number;
    readonly hwpdocument_convertToEditable: (a: number) => [number, number];
    readonly hwpdocument_copyControl: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_copySelection: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_copySelectionInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_createBlankDocument: (a: number) => [number, number];
    readonly hwpdocument_createEmpty: () => number;
    readonly hwpdocument_createHeaderFooter: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_createNumbering: (a: number, b: number, c: number) => number;
    readonly hwpdocument_createShapeControl: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_createTable: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_debugDumpStableIds: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteBookmark: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteCellPictureControlByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_deleteEquationControl: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteFootnote: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteHeaderFooter: (a: number, b: number, c: number, d: number) => void;
    readonly hwpdocument_deletePictureControl: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteRange: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_deleteRangeInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_deleteShapeControl: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteStyle: (a: number, b: number) => number;
    readonly hwpdocument_deleteTableColumn: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_deleteTableControl: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_deleteTableRow: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_deleteText: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_deleteTextInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_deleteTextInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_deleteTextInFootnote: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_deleteTextInHeaderFooter: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_discardSnapshot: (a: number, b: number) => void;
    readonly hwpdocument_ensureDefaultBullet: (a: number, b: number, c: number) => number;
    readonly hwpdocument_evaluateTableFormula: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_exportControlHtml: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_exportHwp: (a: number) => [number, number];
    readonly hwpdocument_exportHwpVerify: (a: number) => [number, number];
    readonly hwpdocument_exportSelectionHtml: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_exportSelectionInCellHtml: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_findNearestControlBackward: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_findNearestControlForward: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_findNextEditableControl: (a: number, b: number, c: number, d: number, e: number) => [number, number];
    readonly hwpdocument_findOrCreateFontIdForLang: (a: number, b: number, c: number, d: number) => number;
    readonly hwpdocument_getBookmarks: (a: number) => [number, number];
    readonly hwpdocument_getBulletList: (a: number) => [number, number];
    readonly hwpdocument_getCanvasKitReplayPlan: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getCaretPosition: (a: number) => [number, number];
    readonly hwpdocument_getCellCharPropertiesAt: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getCellInfo: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getCellInfoByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getCellParaPropertiesAt: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getCellParagraphCount: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
    readonly hwpdocument_getCellParagraphCountByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
    readonly hwpdocument_getCellParagraphLength: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
    readonly hwpdocument_getCellParagraphLengthByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
    readonly hwpdocument_getCellPicturePropertiesByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getCellProperties: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getCellShapePropertiesByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getCellStyleAt: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getCellTextDirection: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
    readonly hwpdocument_getCharPropertiesAt: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getClickHereProps: (a: number, b: number) => [number, number];
    readonly hwpdocument_getClipboardText: (a: number) => [number, number];
    readonly hwpdocument_getColumnDef: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getControlImageData: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getControlImageMime: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getControlTextPositions: (a: number, b: number, c: number) => [number, number];
    readonly hwpdocument_getCursorRect: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getCursorRectByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getCursorRectInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getCursorRectInFootnote: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getCursorRectInHeaderFooter: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getCursorRectInNote: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getDocumentInfo: (a: number) => [number, number];
    readonly hwpdocument_getDpi: (a: number) => number;
    readonly hwpdocument_getEndnoteShape: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getEquationProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getExternalImageBasenames: (a: number) => [number, number];
    readonly hwpdocument_getFieldInfoAt: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_getFieldInfoAtByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
    readonly hwpdocument_getFieldInfoAtInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
    readonly hwpdocument_getFieldList: (a: number) => [number, number];
    readonly hwpdocument_getFieldValue: (a: number, b: number) => [number, number];
    readonly hwpdocument_getFieldValueByName: (a: number, b: number, c: number) => [number, number];
    readonly hwpdocument_getFootnoteInfo: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getFormObjectAt: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getFormObjectInfo: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getFormValue: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getHeaderFooter: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getHeaderFooterList: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_getHeaderFooterParaInfo: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getHeaderFooterPictureProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getLineInfo: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getLineInfoInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getNoteEditInfo: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getNoteEquationProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
    readonly hwpdocument_getNumberingList: (a: number) => [number, number];
    readonly hwpdocument_getPageBorderFill: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getPageControlLayout: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getPageDef: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getPageFootnoteInfo: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_getPageInfo: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getPageLayerTree: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getPageLayerTreeWithProfile: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getPageOfPosition: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_getPageOverlayImages: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getParaPropertiesAt: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_getParaPropertiesInFootnote: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getParaPropertiesInHf: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getParagraphCount: (a: number, b: number) => [number, number, number];
    readonly hwpdocument_getParagraphLength: (a: number, b: number, c: number) => [number, number, number];
    readonly hwpdocument_getParagraphStableId: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_getPictureProperties: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getPositionOfPage: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getSectionCount: (a: number) => number;
    readonly hwpdocument_getSectionDef: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getSelectionRects: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_getSelectionRectsInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_getSelectionRectsInFootnote: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getShapeBBox: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getShapeProperties: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getShapeText: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getShowControlCodes: (a: number) => number;
    readonly hwpdocument_getShowTransparentBorders: (a: number) => number;
    readonly hwpdocument_getSourceFormat: (a: number) => [number, number];
    readonly hwpdocument_getStyleAt: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_getStyleDetail: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_getStyleList: (a: number) => [number, number];
    readonly hwpdocument_getTableBBox: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getTableCellBboxes: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getTableCellBboxesByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getTableDimensions: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getTableDimensionsByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getTableProperties: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getTableSignature: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_getTextBoxControlIndex: (a: number, b: number, c: number) => [number, number, number];
    readonly hwpdocument_getTextInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_getTextInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_getTextRange: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_getValidationWarnings: (a: number) => [number, number];
    readonly hwpdocument_groupShapes: (a: number, b: number, c: number) => [number, number];
    readonly hwpdocument_hasInternalClipboard: (a: number) => number;
    readonly hwpdocument_hitTest: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_hitTestBodyFootnoteMarker: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_hitTestInHeaderFooter: (a: number, b: number, c: number, d: number, e: number) => [number, number];
    readonly hwpdocument_injectExternalImage: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
    readonly hwpdocument_insertColumnBreak: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_insertEndnote: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_insertEquation: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_insertFieldInHf: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_insertFootnote: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_insertNewNumber: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_insertPageBreak: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_insertPicture: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number) => [number, number, number, number];
    readonly hwpdocument_insertTableColumn: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_insertTableRow: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_insertText: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_insertTextInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_insertTextInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_insertTextInFootnote: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_insertTextInHeaderFooter: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_mergeParagraph: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_mergeParagraphInCell: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_mergeParagraphInCellByPath: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_mergeParagraphInFootnote: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_mergeParagraphInHeaderFooter: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_mergeTableCells: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_moveLineEndpoint: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_moveTableOffset: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_moveVertical: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
    readonly hwpdocument_moveVerticalByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_navigateHeaderFooterByPage: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_navigateNextEditable: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
    readonly hwpdocument_new: (a: number, b: number) => [number, number, number];
    readonly hwpdocument_pageCount: (a: number) => number;
    readonly hwpdocument_pasteControl: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_pasteHtml: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_pasteHtmlInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_pasteHtmlInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_pasteInternal: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_pasteInternalInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_pasteInternalInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_plainText: (a: number) => [number, number];
    readonly hwpdocument_reflowLinesegs: (a: number) => number;
    readonly hwpdocument_refreshLayout: (a: number) => void;
    readonly hwpdocument_removeFieldAt: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_removeFieldAtInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
    readonly hwpdocument_renameBookmark: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_renderEquationPreview: (a: number, b: number, c: number, d: number, e: number) => [number, number];
    readonly hwpdocument_renderPageHtml: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_renderPageSvg: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_renderPageToCanvas: (a: number, b: number, c: any, d: number) => [number, number];
    readonly hwpdocument_renderPageToCanvasFiltered: (a: number, b: number, c: any, d: number, e: number, f: number) => [number, number];
    readonly hwpdocument_replaceAll: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_replaceOne: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_replaceText: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_resizeTableCells: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_restoreSnapshot: (a: number, b: number) => [number, number, number, number];
    readonly hwpdocument_saveSnapshot: (a: number) => number;
    readonly hwpdocument_searchAllText: (a: number, b: number, c: number, d: number, e: number) => [number, number];
    readonly hwpdocument_searchText: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_setActiveField: (a: number, b: number, c: number, d: number) => number;
    readonly hwpdocument_setActiveFieldByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
    readonly hwpdocument_setActiveFieldInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
    readonly hwpdocument_setCellPicturePropertiesByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_setCellProperties: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_setCellShapePropertiesByPath: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_setClipEnabled: (a: number, b: number) => void;
    readonly hwpdocument_setColumnDef: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_setDpi: (a: number, b: number) => void;
    readonly hwpdocument_setEquationProperties: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_setFieldValue: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_setFieldValueByName: (a: number, b: number, c: number, d: number, e: number) => [number, number];
    readonly hwpdocument_setFileName: (a: number, b: number, c: number) => void;
    readonly hwpdocument_setFormValue: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_setFormValueInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
    readonly hwpdocument_setHeaderFooterPictureProperties: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
    readonly hwpdocument_setNoteEquationProperties: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
    readonly hwpdocument_setNumberingRestart: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
    readonly hwpdocument_setPageBorderFill: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_setPageDef: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_setPictureProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_setSectionDef: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_setSectionDefAll: (a: number, b: number, c: number) => [number, number];
    readonly hwpdocument_setShapeProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_setShowControlCodes: (a: number, b: number) => void;
    readonly hwpdocument_setShowParagraphMarks: (a: number, b: number) => void;
    readonly hwpdocument_setShowTransparentBorders: (a: number, b: number) => void;
    readonly hwpdocument_setTableProperties: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_splitParagraph: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_splitParagraphInCell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
    readonly hwpdocument_splitParagraphInCellByPath: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_splitParagraphInFootnote: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_splitParagraphInHeaderFooter: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_splitTableCell: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
    readonly hwpdocument_splitTableCellInto: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
    readonly hwpdocument_splitTableCellsInRange: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number, number];
    readonly hwpdocument_toggleHideHeaderFooter: (a: number, b: number, c: number) => [number, number, number, number];
    readonly hwpdocument_ungroupShape: (a: number, b: number, c: number, d: number) => [number, number, number, number];
    readonly hwpdocument_updateClickHereProps: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
    readonly hwpdocument_updateConnectorsInSection: (a: number, b: number) => void;
    readonly hwpdocument_updateStyle: (a: number, b: number, c: number, d: number) => number;
    readonly hwpdocument_updateStyleShapes: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
    readonly hwpdocument_renderPageToCanvasLegacy: (a: number, b: number, c: any, d: number) => [number, number];
    readonly hwpdocument_hitTestFootnote: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_hitTestHeaderFooter: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_hitTestInFootnote: (a: number, b: number, c: number, d: number) => [number, number];
    readonly hwpdocument_exportHwpx: (a: number) => [number, number];
    readonly hwpdocument_ensureDefaultNumbering: (a: number) => number;
    readonly hwpdocument_ensureParagraphStableIds: (a: number) => void;
    readonly hwpdocument_findOrCreateFontId: (a: number, b: number, c: number) => number;
    readonly hwpdocument_createStyle: (a: number, b: number, c: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
